# Generated by Django 3.0.7 on 2020-06-28 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200628_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer_choices',
        ),
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.ManyToManyField(to='api.AnswerChoice'),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='correct_answer', to='api.AnswerChoice'),
            preserve_default=False,
        ),
    ]
